--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RedCraftGH/Crates
branches:
- master
projects:
  Crates:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: 1.1.3
...
