--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RedCraftGH/CubeXSkyblock
branches:
- master
projects:
  CubeXSkyblock:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: 1.1.2
...
